name: al_quran
description: Flutter App for the holy book of Qur'an.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  
  # utils
  shimmer: ^2.0.0
  flutter_overboard: ^3.0.0
  share: ^2.0.4

  # network
  http: ^0.13.4
  url_launcher: ^6.0.12
  
  # state management
  provider: ^6.0.1

  # flutter code
  flutter_lints: ^1.0.4

  # cache
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  shared_preferences: ^2.0.8

  # app info
  package_info_plus: ^1.3.0

  # new update 1.
  audioplayer: 0.8.1
  audioplayer_web: 0.7.1
  path_provider: ^2.0.11
  audioplayers: ^0.20.1
  curved_navigation_bar: ^0.3.0
  scroll_bottom_navigation_bar: ^4.0.0
  duration: ^3.0.11
  flutter_launcher_icons: ^0.9.0
  #/ new update 1.
dev_dependencies:

  # new update 1.
#  flutter_launcher_icons: "^0.7.0"
  #/ new update 1.

  flutter_test:
    sdk: flutter

  # cache local storage
  build_runner: ^2.1.5
  hive_generator: ^1.1.1

# The following section is specific to Flutter.

flutter_icons:
  image_path: "assets/images/logo.png"
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/audio/

  fonts:
    - family: Sogeo
      fonts:
        - asset: fonts/sui.ttf
    #     - asset: fonts/Raleway-Italic.ttf
    #       style: italic
    - family: ShareIcon
      fonts:
        - asset: fonts/ShareIcon.ttf
