name: wealth_earn
description: A new Flutter application.


publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 2.0.0+2


environment:
  sdk: ">=2.16.2 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  # Get timeDate
  intl: ^0.17.0

  cupertino_icons: ^1.0.2

  cached_network_image:

  cool_alert: ^1.1.0

  google_fonts: ^2.1.0

  # Copy text
  clipboard: ^0.1.3

  # Save data
  shared_preferences: ^2.0.6

  # State Management
  get: ^4.6.1

  # uuid
  uuid: ^3.0.6

  # Firebase
  firebase_auth: ^3.4.1
  firebase_database: ^9.0.20
  flutter_login: ^3.1.0
  firebase_core: ^1.6.0
  cloud_firestore: ^3.4.0

  # Ui login
  regexpattern: ^2.0.1

  # Marquee text as news
  marquee: ^2.2.0

  # Introduction app
  introduction_screen: ^2.1.0

  # Image Animator
  widget_circular_animator: ^1.0.0

  # Url Launcher
  url_launcher: ^6.0.3

dev_dependencies:

  flutter_launcher_icons: ^0.9.2

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter_icons:
  image_path: "assets/logo.png"
  android: true
  ios: true


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/welcome_screen/

  fonts:
    - family: AquinoDemo
      fonts:
        - asset: assets/fonts/AquinoDemo.ttf

    - family: Nisebuschgardens
      fonts:
        - asset: assets/fonts/Nisebuschgardens.ttf

    - family: Nunito
      fonts:
        - asset: assets/fonts/NunitoBold.ttf